# Generated by Django 5.2.7 on 2026-02-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genre_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
